### PR TITLE
Header icons

### LINKED ISSUE #2: Add SVG icons for "Run" and "Share"

### PR DESCRIPTION
**Pull request by jodelamo**
Gives header a bit of a (mobile first) makeover.
- SVG icons
- Moves "Go output" checkbox to the editor view
- Moves the "About" button and puts it as a link in the footer
- Various other minor HTML/CSS changes

Fixes #2

### CODE REVIEW

**Comment by owickstrom** [comment]
Maybe we could move the keyboard shortcut stuff to the About page, leaving the top bar buttons cleaner?

**Comment by jodelamo** [comment]
Yeah, wanted to get rid of that myself. I'll move it.

**Comment by jodelamo** [comment]
@owickstrom Ready for another look. :)

**Comment by owickstrom** [comment]
Outstanding!

I reduced the border-radius of the `.show-go-output` button to match the other ones.

**Pull request merged**
